install.packages("ggplot2")
install.packages("glmulti")
install.packages("randomForest")
install.packages("plyr")
install.packages("dplyr")
install.packages("caret")

library(ggplot2)
library(glmulti)
library(plyr)
library(dplyr)
library(caret)
library(mlbench)
library(randomForest)